name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  Linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.11']
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
      - name: Setup pdm
        run: |
          python3 -m pip install pdm
          pdm config python.use_venv false
      - name: Setup Venv outside of pdm to accomodate mypy's PEP
        # https://github.com/pdm-project/pdm/issues/811
        # https://github.com/python/mypy/issues/11477
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install Requirements with pip
        run: |
          pdm export -o requirements.txt --without-hashes
          python3 -m pip install -r requirements.txt
      - name: Run scripts/lint (without pdm)
        run: |
          scripts/lint.sh